### ISSUE TITLE
Non-existent file after mapping

### ISSUE THREAD

**Issue by robertbasic** [robertbasic/pugdebug#130]
```
Traceback (most recent call last):
  File "/home/robert/pugdebug/pugdebug/pugdebug.py", line 564, in handle_step_command
    self.focus_current_line()
  File "/home/robert/pugdebug/pugdebug/pugdebug.py", line 397, in focus_current_line
    document_widget.move_to_line(current_line)
AttributeError: 'NoneType' object has no attribute 'move_to_line'
```

**Comment by robertbasic** [comment]
This got introduced with removing the code that opened the index file on debug start https://github.com/robertbasic/pugdebug/pull/121
