### ISSUE TITLE
Unable to use it at all

### ISSUE THREAD

**Issue by ashnur** [robertbasic/pugdebug#160]
My setup:
- using linux binary
- host machine Arch linux
- guest is a vagrant ubuntu box, xdebug chrome app is able to connect to xdebug on it with the same settings

Usually nothing happens, just sits there waiting for connection. No errors or anything. Sometimes, I am able to get these errors (I run pugdebug from terminal):
```
Traceback (most recent call last):
  File "/home/robert/pugdebug/pugdebug/server.py", line 42, in run
  File "/home/robert/pugdebug/pugdebug/server.py", line 88, in __listen
  File "/home/robert/pugdebug/pugdebug/server.py", line 166, in init_connection
KeyError: 'idekey'
```
The idekey is the same for sure obviously.

Because there are not logs to see what pugdebug does (or at least I was unable to find them), I have no idea what else could I check  to see what's the issue.

**Comment by ashnur** [comment]
Also, I don't understand what I see on the guest, in the xdebug.log either:
```
Log opened at 2015-11-11 15:51:26
I: Checking remote connect back address.
I: Remote address found, connecting to 192.168.56.1:8081.
E: Could not connect to client. :-(
Log closed at 2015-11-11 15:51:26
```

The host ip is 192.168.56.1 (the port is changed because of php-fpm), but when the xdebug chrome app connects, xdebug logs the IP 127.0.0.1 and not 192.168.56.1
And I never set 192.168.56.1 neither in pugdebug nor in xdebug config.

**Comment by robertbasic** [comment]
Thanks for the report, I'll look into it!

**Comment by ashnur** [comment]
Would be great if I could use this, the chrome app I mentioned is not very polished :). Let me know if you need more data or have some idea I could try out to give a better description of what's happening.

**Comment by robertbasic** [comment]
Well the traceback shows paths to `/home/robert/...` which is my home path (except if your home folder is also named `robert`, which is a coincidence then :D), and that makes me believe I'm not building the binaries correctly. Will look into that first.

**Comment by robertbasic** [comment]
Hey @ashnur could you write me down your xdebug settings and the setting inside pugdebug? thanks!

**Comment by ashnur** [comment]
I will, but only after monday, I have no access to that machine until then.

**Comment by AnrDaemon** [comment]
I'm afraid to report, I'm in the same boat.
Tried both local and remote debug, local works first few clicks, remote - unable to establish mappings. File named tab pops up in the middle, but content is empty. If I force click the same named file in the browser, it opens new tab with same name.
At the same time the File Browser shows correct root directory, and if I click on any file there, it'll load just all right.

**Comment by AnrDaemon** [comment]
![CRY](http://forum.ubuntu.ru/Smileys/webby/cry.gif)

**Comment by ashnur** [comment]
I haven't had to deal with PHP since, so I never got to write down the exact xdebug and pugdebug settings. Maybe you could do that @AnrDaemon ?

**Comment by AnrDaemon** [comment]
I've tried many combinations, but no matter how hard I try, the thing just doesn't work.
At all.
Local or remote files.
Any combination of settings for xdebug and pugdebug.
Just… No result. Hangs. Empty windows. So sad.
If it stays like this, I'll have no choice but to write my own crutch :(

**Comment by ashnur** [comment]
@AnrDaemon I think it would be very useful if you would share at least known combination from the many you have tried that is not working. You must realize that if it would be trivial to debug this, it would be solved already, so something must be out of place, maybe there is a hidden assumption that breaks or something. 
Also, you could share some logs too, same way I did...

**Comment by AnrDaemon** [comment]
https://github.com/robertbasic/pugdebug/issues/168

**Comment by jlownie** [comment]
I'm having what I think is the same problem.  pugdebug doesn't get a connection from the debug engine, it just sits there "Waiting for connection".  The program debugclient included with the xdebug package does get the connection and starts a debug session, so I know xdebug works.  I tried executing php both from the command line and from the browser, neither worked.  The remote code is on a web server on the same machine pugdebug is running on.

It would be good to be able to get more information about what pugdebug is doing.  Nothing is appearing in the terminal window that I started pugdebug from.

I'm using Fedora 25.  Here are my xdebug settings:

[xdebug]
zend_extension=/usr/lib64/php/modules/xdebug.so
xdebug.remote_enable=1
xdebug.remote_connect_back=0
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.show_local_vars=0
xdebug.var_display_max_data=10000
xdebug.var_display_max_depth=20
xdebug.show_exception_trace=0
xdebug.idekey=pugdebug

My pugdebug settings:

Root: /home/jlownie/www/
Host: localhost
Port: 9000
IDE Key: pugdebug

**Comment by jlownie** [comment]
Disregard my previous message, the issue was the ide key which wasn't what I thought it was.  When I removed the ide key from pugdebug and started it listening, it picked up the session OK.

**Comment by gmarkow** [comment]
Not sure if this is a help to anyone but I had a similar issue. Running on Mint, pugdebug never caught a connection. **I got it working by changing "Host" under settings from 127.0.0.1 to a blank field**. Then bang everything worked.

**Comment by AnrDaemon** [comment]
At this point, VSCode won the day by a VERY large margin.
