### ISSUE TITLE
Error running the binary

### ISSUE THREAD

**Issue by robertbasic** [robertbasic/pugdebug#204]
Reported by @ldusan84

```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/home/robert/pugdebug/env/lib/python3.4/site-packages/PyInstaller-3.0.dev0-py3.4.egg/PyInstaller/loader/pyi_importers.py", line 308, in load_module
  File "/home/robert/pugdebug/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 22, in <module>
  File "/home/robert/pugdebug/env/lib/python3.4/site-packages/PyInstaller-3.0.dev0-py3.4.egg/PyInstaller/loader/pyi_importers.py", line 478, in load_module
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /tmp/_MEIRxol54/time.cpython-34m.so)
```

I'm guessing on a Ubuntu install.

**Comment by ldusan84** [comment]
@robertbasic yes, on Ubuntu 12.04.

**Comment by robertbasic** [comment]
The problem is old glibc on Ubuntu 12.04.

PyInstaller does bundle everything pugdebug needs, except system libraries.

http://www.lightofdawn.org/wiki/wiki.cgi/NewAppsOnOldGlibc
https://github.com/pyinstaller/pyinstaller/wiki/FAQ#gnulinux

**Comment by ldusan84** [comment]
@robertbasic got it. So what should I do after all?

**Comment by robertbasic** [comment]
@ldusan84 I think this is up to me to figure out what would be the oldest system to support, and build the executables for pugdebug on that, so more users can use it.

The end goal is to make running and using pugdebug as painless as possible.

**Comment by robertbasic** [comment]
On Fedora 25 it fails with:

```
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/home/robert/pugdebug/env/lib/python3.4/site-packages/PyInstaller-3.0.dev0-py3.4.egg/PyInstaller/loader/pyi_importers.py", line 478, in load_module
ImportError: /lib64/libGL.so.1: undefined symbol: drmFreeDevice
```

**Comment by jaimealsilva** [comment]
I'm getting the following error in Ubuntu 17.04 Zesty:
```
jaime@r2d2:~/Downloads/pugdebug-1.0.0-linux64$ ./pugdebug 
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/home/robert/pugdebug/env/lib/python3.4/site-packages/PyInstaller-3.0.dev0-py3.4.egg/PyInstaller/loader/pyi_importers.py", line 478, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmFreeDevice
```

**Comment by agarzon** [comment]
Ubuntu 16.04 LTS
```
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/home/robert/pugdebug/env/lib/python3.4/site-packages/PyInstaller-3.0.dev0-py3.4.egg/PyInstaller/loader/pyi_importers.py", line 478, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmFreeDevice

```

**Comment by denised** [comment]
Also on 16.04, a slight variation on argazon's result:
````
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/home/robert/pugdebug/env/lib/python3.4/site-packages/PyInstaller-3.0.dev0-py3.4.egg/PyInstaller/loader/pyi_importers.py", line 478, in load_module
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
````
I'd be happy to do a workaround, if anyone knows what that would be?
