### ISSUE TITLE
Bad file descriptor during...

### ISSUE THREAD

**Issue by ciscon** [robertbasic/pugdebug#207]
If clicking "run" too quickly, many warnings can crop up with the message "Bad file descriptor during" either "stop action" or "step_run action".  This can also result in the application crashing with the following trace:

Traceback (most recent call last):
  File "pugdebug/pugdebug.py", line 640, in handle_debugging_post_start
    self.step_into()
  File "pugdebug/pugdebug.py", line 752, in step_into
    self.debugger.step_into()
  File "pugdebug/debugger.py", line 258, in step_into
    self.current_connection.step_into()
AttributeError: 'NoneType' object has no attribute 'step_into'
Aborted

This happened on both Debian 9 and Mint 18.1

**Comment by IslandUsurper** [comment]
I've seen this problem. But it also occurs when stepping "In" and the error says "post_step action" as well. Is the workaround to be more patient and wait between pressing buttons?

**Comment by robertbasic** [comment]
Thanks for the report and the feedback!

Sadly, pugdebug is not on the top of my priority list now, so it receives little attention from me. I hope it'll change soon, as I quite enjoyed working on it.

Thanks!
