### ISSUE TITLE
Undefined symbol: drmGetDevice2 

### ISSUE THREAD

**Issue by Croxarens** [robertbasic/pugdebug#209]
When I try to run the pugdebug I get the following error : 
symbol lookup error: /usr/lib/libGLX_mesa.so.0: undefined symbol: drmGetDevice2

Didn't find how to fix it.. Anyone had the same problem?

**Comment by bserem** [comment]
Similar issue here:

```
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/home/robert/pugdebug/env/lib/python3.4/site-packages/PyInstaller-3.0.dev0-py3.4.egg/PyInstaller/loader/pyi_importers.py", line 478, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/libGL.so.1: undefined symbol: drmFreeDevice
```

Btw, i guess robert in the path above is @robertbasic, cause this is not a path in my system.

**Comment by baptx** [comment]
@bserem I also had the similar issue with drmFreeDevice message (https://github.com/robertbasic/pugdebug/issues/210), I could not get the binary file to work which also looks very big (the tar.gz archive is 80 MB and the source code tar.gz archive is 44 KB).
I got pugdebug working by downloading the source code and running `python3 app.py`.
On Ubuntu 16.04 LTS, I had to install some dependencies first:
`sudo apt install python3-pyqt5`
`sudo apt install python3-pygments`

**Comment by leonstafford** [comment]
You may also need `sudo apt install python3-fuzzywuzzy`
