### ISSUE TITLE
Crash on adding breakpoints

### ISSUE THREAD

**Issue by Mte90** [robertbasic/pugdebug#212]
When I doubleclick on a line the app crashes with this output:
```QIODevice::read (QFile, "/srv/www/boilerplate/htdocs/index.php"): device not open
inotify_add_watch("/srv/www/boilerplate/htdocs/index.php") failed: "No such file or directory"
Traceback (most recent call last):
  File "/tmp/pugdebug/pugdebug/pugdebug.py", line 932, in handle_breakpoints_listed
    document_widget = self.document_viewer.get_document_by_path(path)
  File "/tmp/pugdebug/pugdebug/gui/documents.py", line 73, in get_document_by_path
    return self.widget(index)
TypeError: widget(self, int): argument 1 has unexpected type 'NoneType'
```
I understood that the issue is that I have to invert the path in the settings.
Maybe add a check if file exists with a warning can be better.

**Comment by Mte90** [comment]
This is fixed in the fork at https://github.com/Mte90/pugdebug/
